### PR TITLE
Add setuptools, fix nightly?

### LINKED ISSUE #1413: Python job fails on nightly: Missing `setuptools`
Nightly is failing. [setuptools is missing](https://github.com/opendp/opendp/actions/runs/8369403837/job/22915415668#step:6:38):
```
Build bdist
$ (cd python && python setup.py bdist_wheel -d wheelhouse)
Traceback (most recent call last):
  File "/home/runner/work/opendp/opendp/python/setup.py", line 1, in <module>
    from setuptools import setup  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'setuptools'
Error: Process completed with exit code 1.
```

Easy fix?

Also, consider adding a nightly status badge on the README so this will be a higher priority for us going forward.

### PR DESCRIPTION
**Pull request by mccalluc**
- hopefully fix #1413
- follow-up to #1415
- related to #1426 -- with each script having its own requirements, it's easy to get confused and not add dependencies where needed. Since debugging the CI is annoying, it would be good to make this simpler and more robust.

Will file as draft and start a dry-run: https://github.com/opendp/opendp/actions/runs/8424738627

### CODE REVIEW

**Comment by mccalluc** [comment]
[One notebook failed](https://github.com/opendp/opendp/actions/runs/8424705715/job/23069373380#step:9:21):

```
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/nbclient/client.py", line 503, in _async_cleanup_kernel
    assert self.km is not None
AssertionError
.............F....                                                       [100%]
=================================== FAILURES ===================================
_ /home/runner/work/opendp/opendp/docs/source/api/user-guide/measurements/pca.ipynb _
[gw1] linux -- Python 3.9.18 /opt/hostedtoolcache/Python/3.9.18/x64/bin/python
NBMAKE INTERNAL ERROR
Kernel didn't respond in 60 seconds
```

Will restart that job. Don't bother with an issue unless we see this again.

**Comment by mccalluc** [comment]
Also a problem with the nightly build from this branch. What's strange is [this](https://github.com/opendp/opendp/actions/runs/8424738627/job/23070042388#step:6:20):
```
pip install wheel
```

Did I modify the wrong file? Investigating...

**Comment by mccalluc** [comment]
Understand it a little better: The checkout action uses the channel parameter, not the current development branch. To actually run the changes in this branch, select `dev` and `sync`, and I've just started a run with that: https://github.com/opendp/opendp/actions/runs/8429756682

`channel_tool.py`
```python
        channel_to_upstream = {"dev": get_current_branch(), "nightly": "main", "beta": "nightly", "stable": "beta"}
        upstream = channel_to_upstream[args.channel] if args.upstream is None else args.upstream
```

**Comment by mccalluc** [comment]
Yay. When I run against the right branch, [it works](https://github.com/opendp/opendp/actions/runs/8429756682/job/23084874831#step:6:15).

Ready for review.

**Review by Shoeboxam — APPROVED** [review]
We have another requirements file blooming under our very noses in the `python_build.sh` file! They come from everywhere! Thanks for tracking this down.

**Pull request merged**
