### PR TITLE
updated First-Look-at-DP notebook

### LINKED ISSUE #1269: Updated First-Look-At-DP notebook
This material was adapted from a notebook for the Sydney Privacy Workshop

### PR DESCRIPTION
**Pull request by Shoeboxam**
Closes #1269

### CODE REVIEW

**Comment by Shoeboxam** [comment]
Current dependencies on/for this PR:
* `main`
  * **PR #1270** <a href="https://app.graphite.dev/github/pr/opendp/opendp/1270?utm_source=stack-comment-icon" target="_blank">Graphite</a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/opendp/opendp/1270?utm_source=stack-comment).

**Comment by mccalluc** [comment]
I'm going to take the updated notebook content here, and make a PR against `docs-IN-PROGRESS` (where it is in RST instead of a notebook). That branch currently has TODOs on the corresponding page.

This PR could still be merged, if we want something in sooner.

**Comment by mccalluc** [comment]
With #1278 merged, I'd suggest closing this, and getting `docs-IN-PROGRESS` merged to `main`. This is a really clear explanation, and I didn't make many changes translating it to RST.

**Comment by Shoeboxam** [comment]
Thanks for adapting this @mccalluc!

**Pull request closed without merging**
