### PR TITLE
rename AllDomain -> AtomDomain, OptionNullDomain -> OptionDomain

### PR DESCRIPTION
**Pull request by Shoeboxam**
* Rename `OptionNullDomain` to `OptionDomain` 
* Rename `AllDomain` to `AtomDomain`

This is a part of the runtime descriptors PR.

### CODE REVIEW

**Comment by Shoeboxam** [comment]
Current dependencies on/for this PR:
* main
  * **PR #696** <a href="https://app.graphite.dev/github/pr/opendp/opendp/696" target="_blank">Graphite</a>  👈
    * **PR #645** <a href="https://app.graphite.dev/github/pr/opendp/opendp/645" target="_blank">Graphite</a> 
      * **PR #604** <a href="https://app.graphite.dev/github/pr/opendp/opendp/604" target="_blank">Graphite</a> 
        * **PR #687** <a href="https://app.graphite.dev/github/pr/opendp/opendp/687" target="_blank">Graphite</a> 
          * **PR #688** <a href="https://app.graphite.dev/github/pr/opendp/opendp/688" target="_blank">Graphite</a> 
            * **PR #689** <a href="https://app.graphite.dev/github/pr/opendp/opendp/689" target="_blank">Graphite</a> 
              * **PR #690** <a href="https://app.graphite.dev/github/pr/opendp/opendp/690" target="_blank">Graphite</a> 
                * **PR #512** <a href="https://app.graphite.dev/github/pr/opendp/opendp/512" target="_blank">Graphite</a> 
                * **PR #692** <a href="https://app.graphite.dev/github/pr/opendp/opendp/692" target="_blank">Graphite</a> 
                  * **PR #514** <a href="https://app.graphite.dev/github/pr/opendp/opendp/514" target="_blank">Graphite</a> 
      * **PR #691** <a href="https://app.graphite.dev/github/pr/opendp/opendp/691" target="_blank">Graphite</a> 

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/opendp/opendp/696?utm_source=stack-comment).

**Comment by Shoeboxam** [comment]
Current dependencies on/for this PR:
* main
  * **PR #696** <a href="https://app.graphite.dev/github/pr/opendp/opendp/696" target="_blank">Graphite</a>  👈
    * **PR #645** <a href="https://app.graphite.dev/github/pr/opendp/opendp/645" target="_blank">Graphite</a> 
      * **PR #604** <a href="https://app.graphite.dev/github/pr/opendp/opendp/604" target="_blank">Graphite</a> 
        * **PR #687** <a href="https://app.graphite.dev/github/pr/opendp/opendp/687" target="_blank">Graphite</a> 
          * **PR #688** <a href="https://app.graphite.dev/github/pr/opendp/opendp/688" target="_blank">Graphite</a> 
            * **PR #689** <a href="https://app.graphite.dev/github/pr/opendp/opendp/689" target="_blank">Graphite</a> 
              * **PR #690** <a href="https://app.graphite.dev/github/pr/opendp/opendp/690" target="_blank">Graphite</a> 
                * **PR #512** <a href="https://app.graphite.dev/github/pr/opendp/opendp/512" target="_blank">Graphite</a> 
                * **PR #692** <a href="https://app.graphite.dev/github/pr/opendp/opendp/692" target="_blank">Graphite</a> 
                  * **PR #514** <a href="https://app.graphite.dev/github/pr/opendp/opendp/514" target="_blank">Graphite</a> 
      * **PR #691** <a href="https://app.graphite.dev/github/pr/opendp/opendp/691" target="_blank">Graphite</a> 

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/opendp/opendp/696?utm_source=stack-comment).

**Comment by Shoeboxam** [comment]
Current dependencies on/for this PR:
* main
  * **PR #696** <a href="https://app.graphite.dev/github/pr/opendp/opendp/696" target="_blank">Graphite</a>  👈
    * **PR #645** <a href="https://app.graphite.dev/github/pr/opendp/opendp/645" target="_blank">Graphite</a> 
      * **PR #604** <a href="https://app.graphite.dev/github/pr/opendp/opendp/604" target="_blank">Graphite</a> 
        * **PR #687** <a href="https://app.graphite.dev/github/pr/opendp/opendp/687" target="_blank">Graphite</a> 
          * **PR #688** <a href="https://app.graphite.dev/github/pr/opendp/opendp/688" target="_blank">Graphite</a> 
            * **PR #689** <a href="https://app.graphite.dev/github/pr/opendp/opendp/689" target="_blank">Graphite</a> 
              * **PR #690** <a href="https://app.graphite.dev/github/pr/opendp/opendp/690" target="_blank">Graphite</a> 
                * **PR #512** <a href="https://app.graphite.dev/github/pr/opendp/opendp/512" target="_blank">Graphite</a> 
                * **PR #692** <a href="https://app.graphite.dev/github/pr/opendp/opendp/692" target="_blank">Graphite</a> 
                  * **PR #514** <a href="https://app.graphite.dev/github/pr/opendp/opendp/514" target="_blank">Graphite</a> 
      * **PR #691** <a href="https://app.graphite.dev/github/pr/opendp/opendp/691" target="_blank">Graphite</a> 

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/opendp/opendp/696?utm_source=stack-comment).

**Review by andrewvyrros — APPROVED** [review]
Thanks kindly for splitting off a separate rename PR! This will make reviewing #645 much easier.

**Comment by Shoeboxam** [comment]
@andrewvyrros Absolutely! I don't mind making changes to ease review.

**Pull request merged**
