### PR TITLE
Add `rustfmt` in CI

### PR DESCRIPTION
**Pull request by mccalluc**
- Towards #256

Filing as draft. There are a lot of warnings, locally and on CI. Since there are lots of PRs out right now, making changes to the formatting in this branch would just mean a lot of merge conflict headaches. Instead I'd suggest that the Rust PRs that are out now should be formatted before being merged, then this branch can be updated, and hopefully we'll have just a a few remaining formatting issues to address.

### CODE REVIEW

**Comment by mccalluc** [comment]
@Shoeboxam -- It's probably in your court to decide whether this would be useful or not. For the other CI checks, I've been checking in a long list of ignores, but:
- You might not be interested in any of these automated suggestions
- There don't seem to be [config options](https://rust-lang.github.io/rustfmt/?version=master&search=) to just ignore most formatting rules -- Instead the options let you pick from a set.

An alternative or complement would be to run clippy in CI. Your call?

**Review by Shoeboxam — CHANGES_REQUESTED** [review]
This has come up in some previous discussions, the downside being that it's another step for new contributors, but I think this is a particularly small step. It will also help reduce reformatting diffs in unrelated PRs. So I'm generally positive on adding rustfmt to CI. I don't think we should add clippy at this point.

* Can you move the check to before the build step, so that potential failures happen more quickly?
* I think a reformatting PR should be merged first, so that this PR's CI can pass.

**Comment by Shoeboxam** [comment]
Two more changes to improve end-user experience:
1. Use `cargo fmt --all -- --check` instead. It's clearer that `cargo fmt --all` will work.
2. Update the step name to something more descriptive, like `Check formatting (cargo fmt --all)`

**Comment by mccalluc** [comment]
... was actually expecting a failure... unless this is a different set of styling rules? Need to investigate.

**Comment by Shoeboxam** [comment]
> ... was actually expecting a failure... unless this is a different set of styling rules? Need to investigate.

It succeeded because the `||`: if the fmt check fails, then the echo will still succeed, returning exit status 0.

**Comment by mccalluc** [comment]
[Twenty minutes ago](https://github.com/opendp/opendp/actions/runs/7183438533/job/19562225105#step:4:9) version was 1.74.0.

[Latest run](https://github.com/opendp/opendp/actions/runs/7183664151/job/19562948334#step:4:9) version is 1.74.1.

**Review by raprasad — APPROVED** [review]
approved

**Pull request merged**
