### PR TITLE
Add a couple more generated files to gitignore list

### LINKED ISSUE #2019: Consider .gitignore-ing NAMESPACE
Unrelated: Guessing it's something that was missed and we're just catching up with? Is there an issue to either generate this file, or check for missing items?

_Originally posted by @mccalluc in https://github.com/opendp/opendp/pull/1768#discussion_r1747569531_

Mike: yes, this was missed earlier.

### PR DESCRIPTION
**Pull request by mccalluc**
- Fix #2019

### CODE REVIEW

**Comment by mccalluc** [comment]
- Hit #2051 again. Rerunning.

**Comment by Shoeboxam** [comment]
There's a bootstrap problem here where NAMESPACE must exist for NAMESPACE to be updated. In addition, the `useDynLib(opendp, .registration = TRUE)` might be hand-written? Maybe we just gitignore the .h file and leave NAMESPACE for now.

**Review by Shoeboxam — CHANGES_REQUESTED** [review]
There's a bootstrap problem here where NAMESPACE must exist for NAMESPACE to be updated. In addition, the `useDynLib(opendp, .registration = TRUE)` might be hand-written? Maybe we just gitignore the .h file and leave NAMESPACE for now.

**Review by Shoeboxam — APPROVED** [review]
Looks good to me now!

**Pull request merged**
