### PR TITLE
Change: update URLs to reflect new structure

### LINKED ISSUE #1691: Make sure links to stable don't break with new docs
With the new docs structure, some urls are changing. For example: `/contributor/index.html` -> `/contributing/index.html`. Inside the docs themselves, most links are relative, and are already correct, but in the READMEs there are are some absolute URLs. Proposal:

- Search and replace `/en/stable` -> `/en/nightly`.
- Run link checking: Should find ones that need to be fixed.
- Fix them.
- Release new docs.
- Search and replace `/en/nightly` -> `/en/stable`.
- Close this issue.

### PR DESCRIPTION
**Pull request by mccalluc**
- Fix #1691 

(Originally planned to do this in two steps, but since the release is out, one step is fine.)

### CODE REVIEW

**Comment by mccalluc** [comment]
Ah: The READMEs are checked weekly, not with every commit. 
```
find .. | grep '.md$' | grep -v 'venv/\|.git/\|CHANGELOG\|vendor/\|R/opendp/README.md' \
          | xargs linkchecker --no-warnings -f linkchecker-external.cfg
```
reports 7 errors now. Fixing them now...

**Comment by mccalluc** [comment]
The weekly markdown link check passes locally.

r docs are an exception: They are pushed to the `stable` url, rather than `nightly`:
```
      - name: Download R Docs
        uses: actions/download-artifact@v4
        with:
          name: r_docs
          path: en/stable/api/r
```
I'm a bit confused here
- (See #1675) 

... but it's not something that should block this PR.

**Review by Shoeboxam — CHANGES_REQUESTED** [review]
Can you please drop the changes from stable to nightly where appropriate? Thanks!

**Review by Shoeboxam — APPROVED** [review]
Thanks! These changes look good to me. There's one spot where we used to intentionally link contributors to nightly docs, but I'm ok with stable nowadays.

**Pull request merged**
