### PR TITLE
parallel directory for ancillary doc files

### LINKED ISSUE #1367: Move code examples into subdirectory
Instead of 
```
quickstart.rst
quickstart.py
quickstart.R
```
we want
```
quickstart.rst
quickstart/example.py
quickstart/example.R
```

Longer pages with multiple discrete, non-interacting examples might be split into separate files, making the `start-at`/`end-at` tags unnecessary:
```
longer-page.rst
longer-page/feature-abc.py
longer-page/feature-abc.R
longer-page/feature-xyz.py
longer-page/feature-xyz.R
```
If any of the `index.rst` pages had code samples, then there would be a `index/` directory... but our index pages are generally thin.

### PR DESCRIPTION
**Pull request by mccalluc**
- Fix #1367

I think this reflects the consensus we reached; Sorry if I've confused any details.

### CODE REVIEW

**Review by Shoeboxam — COMMENTED** [review]
I'm now recalling an earlier conversation where we didn't nest things under a folder; I think the flip-flop was because I didn't recall the final decision while we were talking in-person. There isn't an obvious best-choice here. 

Was one of your suggestions to have the structure be:

```
quickstart.rst
typical-workflow.rst
code/
    quickstart-context.rst
    quickstart-framework.rst
    quickstart.R
    quickstart.rs
    typical-workflow-context.rst
    typical-workflow-framework.rst
    typical-workflow.R
    typical-workflow.rs
```

This would help to hide the file clutter while navigating the docs.

**Comment by mccalluc** [comment]
Sure: I can do that. There might also be images under `code`, unless we'd like a separate directory for those?

**Comment by mccalluc** [comment]
decided to just put it all under `code` -- This seems simple and clear enough.

**Review by raprasad — APPROVED** [review]
Approved in standup with @mccalluc @Shoeboxam

**Review by raprasad — APPROVED** [review]
approved

**Pull request merged**
