### PR TITLE
Restructured Python project:

### PR DESCRIPTION
**Pull request by andrewvyrros**
* Created Python package.
* Reworked library initialization.
* Added unit test skeleton.
* Added pip requirements.

### CODE REVIEW

**Comment by andrewvyrros** [comment]
I want to clean up the package stuff a bit so it will plug into GitHub Actions.

**Comment by andrewvyrros** [comment]
I added a simple setuptools config. Next will be to run Python tests as part of the build validation action.

With a little more work, we should be able to drive everything from GitHub Actions, including pushing releases to PyPi & crates.io.

**Comment by andrewvyrros** [comment]
Rebased after the samplers change.

**Review by Shoeboxam — APPROVED** [review]
Looks great!

**Pull request merged**
