### PR TITLE
Clean up old maintainer notes

### PR DESCRIPTION
**Pull request by mccalluc**
Most of the material in maintainer-notes was
- covered by the workflow docs
- or covered by the contribution process
- or out of date. (#927)

Also: de-emphasized the rust and proof init docs, but linked them from the appropriate sections of development-environment.

### CODE REVIEW

**Comment by mccalluc** [comment]
> Why de-emphasize these sections of the docs? The proofs intro in particular seems important, and it now has an external link from the invites so I'd be careful that the URL doesn't change.

Let me move the init sections back where they were for URL stability. For someone trying to get started, I worry that this page can be intimidating. I guess I'd like a path where there's enough information about Rust so they can build the software, without getting in mired in other details.

**Comment by mccalluc** [comment]
(The new mini-toctrees I think are an improvement because they offer more information at the point where there might be questions just about Rust or about proof writing.)

**Comment by mccalluc** [comment]
Not urgent, but would like to get this merged before adding a note on the cargo build for R:
- #1918

**Review by Shoeboxam — APPROVED** [review]
Changes look good now. I think the READMEs are a better location for the maintainer notes anyways.

**Pull request merged**
