### PR TITLE
Create CODE_OF_CONDUCT.md

### PR DESCRIPTION
**Pull request by raprasad**
Code of conduct for:
- #542

### CODE REVIEW

**Review by mccalluc — COMMENTED** [review]
- Would it be worth setting up an email account separate from info@opendp.org to handle this?
- Do we know who the "community leaders" are? Who responds if we do receive something? If it's not one of the groups here https://opendp.org/our-people, could we add a section for the "community leaders"?

As much as this Code of Conduct sets expectations for contributors, I think it also commits us to respond clearly, quickly, and consistently. Are we set up for that?

**Review by raprasad — COMMENTED** [review]
- Adapt the Django conduct enforcement manual
- Need people in place, exec committee approval

**Comment by mccalluc** [comment]
Also, might be obvious, but any reports should be treated with care: I'll not sure who gets cc'd on the `info` emails, but it could be easy to forget that it also is used for this.

And, as long as we're under Harvard, should the Title IX Office be mentioned as another route for addressing complaints?

**Comment by mccalluc** [comment]
- close in favor of #1905

**Pull request closed without merging**
