### PR TITLE
Move from 2 checkboxes to one pulldown

### LINKED ISSUE #1365: 3 option pull down: real / dry-run / fake
the fourth combo doesn't make sense

### PR DESCRIPTION
**Pull request by mccalluc**
- Fix #1365

Filing as draft; want to exercise it before review.

### CODE REVIEW

**Comment by mccalluc** [comment]
- Trying a fake run with the new options: https://github.com/opendp/opendp/actions/runs/8334264668 -- [fails](https://github.com/opendp/opendp/actions/runs/8334264668/job/22807550251#step:5:12)
  - Do we know that fake builds are working on main?
- Trying a dry-run: https://github.com/opendp/opendp/actions/runs/8334328445 -- expecting failure because testpypi has already had a version pushed.

I think this is at least worth a review now, to decide what the next steps should be.

**Comment by raprasad** [comment]
@mccalluc note : You can't do multiple dry-runs and have then succeed b/c something already pushed to Test PyPI.

**Comment by mccalluc** [comment]
nightly sync v123 dry-run: https://github.com/opendp/opendp/actions/runs/8363872592

**Comment by mccalluc** [comment]
Rust test failure:
```
---- accuracy::tail_bounds::test::test_empirical_integrate_discrete_gaussian_tail_fixed stdout ----
Discrete Gaussian significance levels/alpha
Theoretical (upper): 0.0013498987536877394
Theoretical (avg):   0.0011393741550945382
Empirical:           0.00152
```
Saw this earlier today, and re-running test fixed it, but should investigate.

**Review by Shoeboxam — APPROVED** [review]
Looks good!

**Pull request merged**
