### PR TITLE
Remove `Any` from generated python

### LINKED ISSUE #1505: Omit bare Any type annotations in generated Python code
No worries: If you haven't already, could you file a follow-up issue? I'd also have a slight preference for no type annotation over `Any`.

_Originally posted by @mccalluc in https://github.com/opendp/opendp/pull/767#discussion_r1560006249_

### PR DESCRIPTION
**Pull request by mccalluc**
- Fix #1505

If this causes any problems, we should just drop it and close the issue, but I think this will make the docs a little more readable.
- The `Any` annotation doesn't add anything in terms of type checking.
- In some cases, it makes the documentation a little confusing, when the semantics of the function make it clear that `Any` is not really the intention.

`Any` tuples may still be in the generated code, but it's not possible to specify a tuple only by length.

### CODE REVIEW

**Review by raprasad — APPROVED** [review]
approved

**Comment by mccalluc** [comment]
New code in main has `Any`s which are no longer generated. I'll resolve.

**Comment by mccalluc** [comment]
[Error from R](https://github.com/opendp/opendp/actions/runs/8803900153/job/24163568527#step:6:30); will try rerunning.

<details>

```
── 1. Error ('test-measurements.R:73:5'): test_gaussian_search ─────────────────
Error in `make_fix_delta(make_zCDP_to_approxDP(then_gaussian(input_space, 
    scale)), delta)`: [FFI] : null pointer: measurement
disabled backtrace
Backtrace:
    ▆
 1. └─opendp::binary_search_param(...) at test-measurements.R:79:3
 2.   └─opendp::binary_search(...) at opendp/R/mod.R:525:3
 3.     └─opendp (local) predicate(mid) at opendp/R/mod.R:584:5
 4.       └─opendp (local) make_chain(param) at opendp/R/mod.R:526:5
 5.         └─opendp (local) make_smd_gauss(s, 1e-05) at test-measurements.R:80:5
Error: Error: Failures detected.
Execution halted
 6.           └─opendp::make_fix_delta(...) at test-measurements.R:73:5
```

</details>

**Review by raprasad — APPROVED** [review]
approved

**Pull request merged**
